version: '2.1'

services:

  postgres:
    image: 'postgres:11.12'
    container_name: db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: app/backend
    container_name: backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - $HOME/upload:/upload
      - $HOME/complete:/complete

#  frontend:
#    image: ''
#
#  watchdog:
#    image: ''
